language: ruby
dist: precise
rvm:
  - 2.4.2
  - 2.3.5
  - 2.2.8
  - 2.1.10
install:
  - sudo cp -a /dev/urandom /dev/random
  - sudo apt-get purge -y gnupg-agent gnupg2
  - bundle install
  - gem build mpw.gemspec
  - gem install mpw-$(cat VERSION).gem
script:
  - rubocop
  - ruby ./test/init.rb
  - ruby ./test/test_config.rb
  - ruby ./test/test_item.rb
  - ruby ./test/test_mpw.rb
  - ruby ./test/test_translate.rb
  - ruby ./test/init.rb
  - ruby ./test/test_cli.rb
  - ruby ./test/test_import.rb
