language: ruby
dist: precise
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
install:
  - bundle install
  - echo 9999 > VERSION
  - gem build mpw.gemspec
  - gem install mpw-9999.gem
script:
  - rubocop
  - ruby ./test/init.rb
  - ruby ./test/test_config.rb
  - ruby ./test/test_item.rb
  - ruby ./test/test_mpw.rb
  - ruby ./test/test_translate.rb
  - ruby ./test/init.rb
  - ruby ./test/test_cli.rb
  - ruby ./test/test_import.rb
