#!/usr/bin/ruby
# author: nishiki
# mail: nishiki@yaegashi.fr
# info: a simple script who manage your passwords

require 'rubygems'
require 'pathname'

APP_ROOT = File.dirname(Pathname.new(__FILE__).realpath)
require "#{APP_ROOT}/CliSSH.rb"

if ARGV.length != 1
	puts "Usage: mpw-ssh search"
	exit 2
end

search = ARGV[0]

cli = CliSSH.new()
cli.ssh(search)

exit 0
